-- =====================================================================
-- ScoutBeyond Database Schema (Supabase / PostgreSQL)
-- AI-Assisted Physical Technology Research for Industrial R&D
-- =====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. RESEARCH SESSIONS / PROBLEMS
-- Stores problem intake, structured briefs, and session snapshots
CREATE TABLE IF NOT EXISTS public.problems (
    id TEXT PRIMARY KEY,
    raw_input TEXT,
    statement TEXT,
    primary_scope TEXT,
    adjacent_scope TEXT,
    status TEXT DEFAULT 'in_progress' CHECK (status IN ('draft', 'in_progress', 'complete', 'error')),
    confidence_level TEXT DEFAULT 'Medium' CHECK (confidence_level IN ('Low', 'Medium', 'High')),
    confidence_note TEXT,
    goals JSONB DEFAULT '[]'::jsonb,
    constraints JSONB DEFAULT '[]'::jsonb,
    assumptions JSONB DEFAULT '[]'::jsonb,
    unknowns JSONB DEFAULT '[]'::jsonb,
    search_dimensions JSONB DEFAULT '[]'::jsonb,
    data JSONB DEFAULT '{}'::jsonb, -- Flexible payload for backwards compatibility with backend storage.py
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Index for problem lookups & recent history
CREATE INDEX IF NOT EXISTS idx_problems_created_at ON public.problems (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_problems_status ON public.problems (status);

-- 3. CANDIDATE TECHNOLOGIES / SOLUTION PRINCIPLES
-- Grouped into Established, Adjacent, and Exploratory
CREATE TABLE IF NOT EXISTS public.candidates (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.problems(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    principle TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('established', 'adjacent', 'exploratory')),
    summary TEXT,
    relevance TEXT,
    industries JSONB DEFAULT '[]'::jsonb,
    physical_mechanisms JSONB DEFAULT '[]'::jsonb,
    maturity_label TEXT,
    maturity_trl INT CHECK (maturity_trl BETWEEN 1 AND 9),
    overall_score NUMERIC(5,2),
    benefits JSONB DEFAULT '[]'::jsonb,
    limitations JSONB DEFAULT '[]'::jsonb,
    uncertainties JSONB DEFAULT '[]'::jsonb,
    sustainability JSONB DEFAULT '{}'::jsonb,
    evidence_count INT DEFAULT 0,
    is_selected BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_candidates_session_id ON public.candidates (session_id);
CREATE INDEX IF NOT EXISTS idx_candidates_category ON public.candidates (category);
CREATE INDEX IF NOT EXISTS idx_candidates_score ON public.candidates (overall_score DESC);

-- 4. EVIDENCE & SOURCES
-- Rigorously evaluated sources with empirical engineering data
CREATE TABLE IF NOT EXISTS public.sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.problems(id) ON DELETE CASCADE,
    candidate_id TEXT REFERENCES public.candidates(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    source_type TEXT DEFAULT 'industry_source' CHECK (
        source_type IN (
            'research_paper', 'patent', 'supplier', 'research_institution', 
            'technical_article', 'industry_source', 'internal', 'other'
        )
    ),
    tier TEXT DEFAULT 'TIER_2_TECHNICAL_SPEC',
    publisher TEXT,
    metrics TEXT,
    snippet TEXT,
    finding TEXT,
    relevance TEXT,
    stance TEXT DEFAULT 'supports' CHECK (stance IN ('supports', 'contradicts', 'neutral')),
    credibility_score INT DEFAULT 80 CHECK (credibility_score BETWEEN 0 AND 100),
    empirical_density_score INT DEFAULT 0 CHECK (empirical_density_score BETWEEN 0 AND 100),
    is_credible BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_sources_session_id ON public.sources (session_id);
CREATE INDEX IF NOT EXISTS idx_sources_candidate_id ON public.sources (candidate_id);
CREATE INDEX IF NOT EXISTS idx_sources_tier ON public.sources (tier);

-- 5. COMPARISON / EVALUATION MATRIX
-- Transparent scoring across engineering criteria
CREATE TABLE IF NOT EXISTS public.evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.problems(id) ON DELETE CASCADE,
    candidate_id TEXT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    criterion_name TEXT NOT NULL,
    score_pill TEXT NOT NULL, -- e.g. "High", "Medium", "Low", "Strong", "Limited"
    css_class TEXT DEFAULT 'medium' CHECK (css_class IN ('high', 'medium', 'low', 'unknown')),
    score_num INT CHECK (score_num BETWEEN 1 AND 5),
    rationale TEXT,
    link_label TEXT,
    confidence TEXT DEFAULT 'medium' CHECK (confidence IN ('low', 'medium', 'high')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    UNIQUE(session_id, candidate_id, criterion_name)
);

CREATE INDEX IF NOT EXISTS idx_evaluations_session ON public.evaluations (session_id);
CREATE INDEX IF NOT EXISTS idx_evaluations_candidate ON public.evaluations (candidate_id);

-- 6. SHORTLIST & INVESTIGATION ROADMAP
CREATE TABLE IF NOT EXISTS public.shortlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.problems(id) ON DELETE CASCADE,
    candidate_id TEXT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    rank INT NOT NULL,
    why_selected TEXT NOT NULL,
    main_uncertainty TEXT,
    next_investigations JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    UNIQUE(session_id, candidate_id)
);

CREATE INDEX IF NOT EXISTS idx_shortlists_session ON public.shortlists (session_id, rank);

-- 7. AUTO-UPDATE TRIGGER FOR PROBLEMS
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_problems_updated_at ON public.problems;
CREATE TRIGGER trigger_problems_updated_at
BEFORE UPDATE ON public.problems
FOR EACH ROW
EXECUTE FUNCTION update_modified_column();

-- 8. ROW LEVEL SECURITY (RLS)
-- Hackathon MVP: Open access for public anonymous users via Supabase anon key
ALTER TABLE public.problems ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.shortlists ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to problems" ON public.problems FOR SELECT USING (true);
CREATE POLICY "Allow public insert to problems" ON public.problems FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to problems" ON public.problems FOR UPDATE USING (true);

CREATE POLICY "Allow public read access to candidates" ON public.candidates FOR SELECT USING (true);
CREATE POLICY "Allow public insert to candidates" ON public.candidates FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to candidates" ON public.candidates FOR UPDATE USING (true);

CREATE POLICY "Allow public read access to sources" ON public.sources FOR SELECT USING (true);
CREATE POLICY "Allow public insert to sources" ON public.sources FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to sources" ON public.sources FOR UPDATE USING (true);

CREATE POLICY "Allow public read access to evaluations" ON public.evaluations FOR SELECT USING (true);
CREATE POLICY "Allow public insert to evaluations" ON public.evaluations FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to evaluations" ON public.evaluations FOR UPDATE USING (true);

CREATE POLICY "Allow public read access to shortlists" ON public.shortlists FOR SELECT USING (true);
CREATE POLICY "Allow public insert to shortlists" ON public.shortlists FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update to shortlists" ON public.shortlists FOR UPDATE USING (true);
